part of 'main.dart';

class AttendanceScreen extends StatefulWidget {final String classId;const AttendanceScreen({super.key,required this.classId});@override State<AttendanceScreen> createState()=>_AttendanceScreenState();}
class _AttendanceScreenState extends State<AttendanceScreen>{late Map<String,String> attendance;final content=TextEditingController();final activities=TextEditingController();final observations=TextEditingController();
  @override void initState(){super.initState(); final students=context.read<AppStore>().studentsOf(widget.classId);attendance={for(final s in students)'${s['id']}':'present'};}
  @override Widget build(BuildContext context){final store=context.watch<AppStore>();final students=store.studentsOf(widget.classId);return Scaffold(appBar:AppBar(title:const Text('Chamada')),body:PagePad(child:ListView(children:[
    Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text('${students.length} alunos',style:Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight:FontWeight.bold)),TextButton(onPressed:()=>setState(()=>attendance.updateAll((k,v)=>'present')),child:const Text('Todos presentes'))]),
    ...students.map((s)=>Card(child:Padding(padding:const EdgeInsets.all(10),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${s['name']}',style:const TextStyle(fontWeight:FontWeight.bold)),const SizedBox(height:8),SegmentedButton<String>(segments:const [ButtonSegment(value:'present',label:Text('Presente')),ButtonSegment(value:'absent',label:Text('Falta')),ButtonSegment(value:'justified',label:Text('Justificada'))],selected:{attendance['${s['id']}']??'present'},onSelectionChanged:(v)=>setState(()=>attendance['${s['id']}']=v.first))]))),
    const SectionTitle('Registro da aula'),TextField(controller:content,maxLines:3,decoration:const InputDecoration(labelText:'Conteúdo ministrado')),const SizedBox(height:10),TextField(controller:activities,maxLines:2,decoration:const InputDecoration(labelText:'Atividades realizadas')),const SizedBox(height:10),TextField(controller:observations,maxLines:2,decoration:const InputDecoration(labelText:'Observações')),const SizedBox(height:16),FilledButton.icon(onPressed:()async{await store.saveLesson({'id':id(),'classId':widget.classId,'date':todayIso(),'content':content.text.trim(),'activities':activities.text.trim(),'observations':observations.text.trim(),'attendance':attendance});if(context.mounted)Navigator.pop(context);},icon:const Icon(Icons.save),label:const Text('Salvar chamada e aula')),
  ])));}
}

Future<void> showLessonForm(BuildContext context,String classId) async {final content=TextEditingController();final activities=TextEditingController();final observations=TextEditingController();var date=todayIso();await showDialog(context:context,builder:(ctx)=>StatefulBuilder(builder:(ctx,setD)=>AlertDialog(title:const Text('Registrar aula'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[ListTile(contentPadding:EdgeInsets.zero,title:const Text('Data'),subtitle:Text(brDate(date)),trailing:const Icon(Icons.calendar_month),onTap:()async{final d=await showDatePicker(context:ctx,firstDate:DateTime(2020),lastDate:DateTime(2035),initialDate:DateTime.parse(date));if(d!=null)setD(()=>date=DateFormat('yyyy-MM-dd').format(d));}),TextField(controller:content,maxLines:3,decoration:const InputDecoration(labelText:'Conteúdo')),const SizedBox(height:10),TextField(controller:activities,maxLines:2,decoration:const InputDecoration(labelText:'Atividades')),const SizedBox(height:10),TextField(controller:observations,maxLines:2,decoration:const InputDecoration(labelText:'Observações'))])),actions:[TextButton(onPressed:()=>Navigator.pop(ctx),child:const Text('Cancelar')),FilledButton(onPressed:(){context.read<AppStore>().saveLesson({'id':id(),'classId':classId,'date':date,'content':content.text.trim(),'activities':activities.text.trim(),'observations':observations.text.trim(),'attendance':<String,String>{}});Navigator.pop(ctx);},child:const Text('Salvar'))]))));}

class CalendarScreen extends StatelessWidget {const CalendarScreen({super.key});@override Widget build(BuildContext context){final s=context.watch<AppStore>();final lessons=[...s.lessons]..sort((a,b)=>'${b['date']}'.compareTo('${a['date']}'));return Scaffold(appBar:AppBar(title:const Text('Calendário / Histórico')),body:PagePad(child:lessons.isEmpty?const Center(child:Text('Nenhuma aula registrada.')):ListView.builder(itemCount:lessons.length,itemBuilder:(ctx,i){final l=lessons[i];final c=s.classes.where((x)=>x['id']==l['classId']).cast<Map<String,dynamic>?>().firstOrNull;return Card(child:ListTile(leading:CircleAvatar(child:Text(brDate('${l['date']}').substring(0,2))),title:Text('${c?['name']??'Turma'}'),subtitle:Text('${l['content']?.toString().isNotEmpty==true?l['content']:'Sem conteúdo informado'}\n${brDate('${l['date']}')}'),isThreeLine:true));}))));}}

class ReportsScreen extends StatelessWidget {const ReportsScreen({super.key});@override Widget build(BuildContext context){final s=context.watch<AppStore>();return Scaffold(appBar:AppBar(title:const Text('Relatórios')),body:PagePad(child:ListView(children:[const Text('Frequência por aluno',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),const SizedBox(height:12),if(s.students.where((x)=>x['active']!=false).isEmpty)const Text('Cadastre alunos e faça chamadas para gerar indicadores.')else ...s.students.where((x)=>x['active']!=false).map((st){final f=s.attendanceForStudent('${st['id']}');final total=f['total']??0;final pct=total==0?0.0:(f['present']??0)/total;return Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${st['name']}',style:const TextStyle(fontWeight:FontWeight.bold)),const SizedBox(height:6),LinearProgressIndicator(value:pct),const SizedBox(height:6),Text(total==0?'Sem chamada registrada':'${(pct*100).toStringAsFixed(1)}% • ${f['present']} presenças • ${f['absent']} faltas • ${f['justified']} justificadas')])));})])));}}

class ProfileScreen extends StatelessWidget {const ProfileScreen({super.key});@override Widget build(BuildContext context){final s=context.watch<AppStore>();final name=TextEditingController(text:s.teacher);return Scaffold(appBar:AppBar(title:const Text('Perfil e configurações')),body:PagePad(child:ListView(children:[const CircleAvatar(radius:42,child:Icon(Icons.person,size:46)),const SizedBox(height:18),TextField(controller:name,decoration:const InputDecoration(labelText:'Nome do professor'),onSubmitted:(v){s.teacher=v.trim().isEmpty?'Professor':v.trim();s.save();}),const SizedBox(height:12),SwitchListTile(value:s.dark,onChanged:(v){s.dark=v;s.save();},title:const Text('Tema escuro'),secondary:const Icon(Icons.dark_mode)),Card(child:ListTile(leading:const Icon(Icons.cloud_off),title:const Text('Modo offline'),subtitle:const Text('Seus dados ficam salvos neste aparelho e funcionam sem internet.'))),Card(child:ListTile(leading:const Icon(Icons.info_outline),title:const Text('Aula Fácil'),subtitle:const Text('Versão 1.0 • diário de classe digital'))),const SizedBox(height:10),FilledButton(onPressed:(){s.teacher=name.text.trim().isEmpty?'Professor':name.text.trim();s.save();ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Perfil salvo.')));},child:const Text('Salvar perfil'))])));}}

extension FirstOrNull<E> on Iterable<E>{E? get firstOrNull=>isEmpty?null:first;}
